/** Approval screen styles — kept in a separate module so the shell file
 *  reads as pure composition (no 200-line StyleSheet at the bottom). */
import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomColor: theme.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerTitle: {
    color: theme.textPrimary,
    fontSize: 12,
    letterSpacing: 3,
    fontWeight: "700",
  },
  tabs: {
    flexDirection: "row",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  tab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 999,
  },
  tabActive: {
    backgroundColor: theme.textPrimary,
    borderColor: theme.textPrimary,
  },
  tabText: {
    color: theme.textMuted,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
  },
  tabTextActive: { color: theme.bg },
  tabBadge: {
    backgroundColor: theme.border,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 18,
    alignItems: "center",
  },
  tabBadgeActive: { backgroundColor: theme.bg },
  tabBadgeText: { color: theme.textMuted, fontSize: 10, fontWeight: "700" },
  tabBadgeTextActive: { color: theme.textPrimary },
  list: { padding: spacing.lg, gap: spacing.md },
  card: {
    flexDirection: "row",
    gap: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
  },
  thumbWrap: { width: 90, height: 90, position: "relative" },
  thumb: { width: 90, height: 90, backgroundColor: theme.border },
  playPill: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  reviewBadge: {
    position: "absolute",
    top: 4,
    left: 4,
    right: 4,
    backgroundColor: "rgba(0,0,0,0.78)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
    gap: 4,
  },
  reviewBadgeText: {
    color: "#FFFFFF",
    fontSize: 8.5,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  reviewedBadge: {
    position: "absolute",
    top: 4,
    left: 4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.success,
    alignItems: "center",
    justifyContent: "center",
  },
  lockedHint: {
    color: theme.textMuted,
    fontStyle: "italic",
    fontSize: 11,
    marginTop: 4,
  },
  cardBody: { flex: 1, gap: 2 },
  cardEyebrow: {
    color: theme.primary,
    fontSize: 9,
    letterSpacing: 2,
    fontWeight: "700",
  },
  cardTitle: { color: theme.textPrimary, fontSize: 14, fontWeight: "600" },
  cardMeta: { color: theme.textMuted, fontSize: 12 },
  cardMetaMuted: { color: theme.textMuted, fontSize: 10, letterSpacing: 1 },
  actionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    flexWrap: "wrap",
  },
  actionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderRadius: 999,
    minWidth: 78,
    alignItems: "center",
  },
  actionBtnText: { fontSize: 10, letterSpacing: 2, fontWeight: "700" },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  emptyText: {
    color: theme.textMuted,
    textAlign: "center",
    fontSize: 12,
    letterSpacing: 1,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderBottomColor: theme.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  toggleLabel: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
  },
  toggleHelp: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  backToHome: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  backToHomeText: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
  },
});
