import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerTitle: {
    color: theme.textPrimary,
    fontSize: 14,
    letterSpacing: 4,
    fontWeight: "600",
  },
  card: {
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
  },
  cardRow: { flexDirection: "row", gap: spacing.md },
  cardEyebrow: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 3,
    marginBottom: spacing.sm,
  },
  cardSub: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2,
    marginTop: spacing.md,
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardLink: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  statsRow: { flexDirection: "row", gap: spacing.sm },
  statBox: {
    flex: 1,
    alignItems: "center",
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
  },
  statValue: { color: theme.primary, fontSize: 24, fontWeight: "700" },
  statLabel: {
    color: theme.textMuted,
    fontSize: 9,
    letterSpacing: 2,
    marginTop: 2,
  },
  phaseRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  phaseLabel: {
    color: theme.textMuted,
    fontSize: 10,
    width: 28,
    letterSpacing: 1,
  },
  phaseBar: { flex: 1, height: 6, backgroundColor: theme.border },
  phaseBarFill: { height: 6, backgroundColor: theme.primary },
  phaseValue: {
    color: theme.textPrimary,
    fontSize: 11,
    width: 24,
    textAlign: "right",
  },
  workshopRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  workshopName: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  workshopMeta: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  workshopCountBox: {
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.primary,
    marginLeft: spacing.sm,
  },
  workshopCount: { color: theme.primary, fontSize: 16, fontWeight: "700" },
  workshopCountLabel: { color: theme.primary, fontSize: 8, letterSpacing: 1 },
  miniCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
    alignItems: "flex-start",
    gap: 4,
  },
  miniCardWarn: { borderColor: "#C8A044" },
  miniValue: { color: theme.textPrimary, fontSize: 22, fontWeight: "700" },
  miniLabel: { color: theme.textMuted, fontSize: 9, letterSpacing: 2 },
  newCol: { flex: 1, alignItems: "center", paddingVertical: spacing.sm },
  newColTitle: { color: theme.textMuted, fontSize: 9, letterSpacing: 2 },
  newColPrimary: {
    color: theme.primary,
    fontSize: 22,
    fontWeight: "700",
    marginTop: 4,
  },
  newColSub: {
    color: theme.textMuted,
    fontSize: 9,
    marginTop: 2,
    textAlign: "center",
  },
  actRow: {
    flexDirection: "row",
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  actAction: { color: theme.textPrimary, fontSize: 12 },
  actActor: { color: theme.textMuted, fontSize: 10, marginTop: 1 },
  actTime: { color: theme.textMuted, fontSize: 10, marginLeft: 8 },
  syncBlock: {
    flexDirection: "row",
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    alignItems: "center",
  },
  syncTitle: { color: theme.textPrimary, fontSize: 12, fontWeight: "600" },
  syncSchedule: { color: theme.textMuted, fontSize: 10, marginTop: 2 },
  syncTime: { color: theme.textSecondary, fontSize: 11 },
  empty: {
    color: theme.textMuted,
    fontSize: 11,
    paddingVertical: spacing.sm,
    fontStyle: "italic",
  },
  generatedAt: {
    color: theme.textMuted,
    fontSize: 10,
    textAlign: "center",
    marginTop: spacing.lg,
    fontStyle: "italic",
  },
  filterCaption: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 1.5,
    fontStyle: "italic",
    marginTop: -spacing.sm,
  },
  errorTitle: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 1,
    marginBottom: spacing.sm,
  },
  errorBody: {
    color: theme.textMuted,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
    paddingHorizontal: spacing.xl,
    marginBottom: spacing.lg,
  },
  retryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: spacing.xl,
    marginTop: spacing.sm,
  },
  retryBtnSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: theme.primary,
  },
  retryBtnText: {
    color: "#0A0A0A",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2.5,
  },
});
