/** Styles shared by RendersScreen + its row/assignment-modal children. */
import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg || theme.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerTitle: {
    color: theme.textPrimary,
    fontSize: 13,
    letterSpacing: 4,
    fontWeight: "600",
  },
  vendorPill: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "600",
    textAlign: "center",
    paddingVertical: spacing.sm,
    backgroundColor: "rgba(184,115,51,0.08)",
  },
  vendorBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: spacing.sm + 2,
    backgroundColor: "rgba(184,115,51,0.08)",
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  vendorBarText: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
  },
  rowActive: { backgroundColor: "rgba(184,115,51,0.08)" },
  unassignRow: {
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    marginBottom: spacing.md,
  },
  uploadBtn: {
    backgroundColor: theme.primary,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  uploadBtnDim: { opacity: 0.6 },
  uploadBtnText: {
    color: "#0A0A0A",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 3,
  },
  sectionLabel: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2.5,
    fontWeight: "700",
    marginBottom: 6,
  },
  sectionHint: {
    color: theme.textMuted,
    fontSize: 11,
    lineHeight: 16,
    marginBottom: spacing.md,
  },
  emptyText: {
    color: theme.textMuted,
    fontSize: 12,
    textAlign: "center",
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.lg,
    lineHeight: 18,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  thumbBtn: { width: 56, height: 56, position: "relative" },
  thumb: { width: 56, height: 56, backgroundColor: "#222" },
  // ▶ overlay shown on video thumbnails so users know taps will play.
  thumbPlayOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
  },
  thumbFallback: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  name: { color: theme.textPrimary, fontSize: 13, fontWeight: "500" },
  meta: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  actBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  actBtnApprove: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  actBtnReject: { borderColor: "#FF6B6B" },
});
