import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    gap: spacing.sm,
  },
  iconBtn: { padding: 4, marginRight: spacing.sm },
  // ---- Step prev/next chevron pill (used in the bottom action row).
  // Sized as `flex: 1` so when nested inside the 4-button mfgAmendRow
  // (PREV | UPDATE | REMOVE COMPLETE | NEXT) each pill gets equal width.
  navPillBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: theme.primary,
    minHeight: 44,
  },
  navPillBtnDim: {
    borderColor: theme.border,
    opacity: 0.5,
  },
  navPillText: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "600",
  },
  // ---- 2-button prev/next row for view-only consumers (client) and
  // for sticking under the primary action in form/forward modes.
  navOnlyRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  headerEyebrow: { color: theme.primary, fontSize: 11, letterSpacing: 3 },
  title: { color: theme.textPrimary, fontSize: 24, fontWeight: "300", marginTop: spacing.sm, lineHeight: 30 },
  desc: { color: theme.textSecondary, fontSize: 13, marginTop: spacing.sm, lineHeight: 20 },
  timestampBox: {
    marginTop: spacing.lg,
    borderWidth: 1,
    borderColor: theme.primary,
    padding: spacing.md,
  },
  tsEyebrow: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  tsValue: { color: theme.textPrimary, fontSize: 16, marginTop: 4 },
  tsSub: { color: theme.textSecondary, fontSize: 11, marginTop: 4 },
  formLabel: { color: theme.primary, fontSize: 10, letterSpacing: 3, marginTop: spacing.lg, marginBottom: spacing.sm },
  input: {
    color: theme.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
    textAlignVertical: "top",
  },
  photosHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: spacing.lg },
  addPhotoBtn: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderColor: theme.primary, paddingHorizontal: spacing.sm, paddingVertical: 6 },
  addPhotoText: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  photoGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.sm },
  photoCell: { width: 84, height: 84, position: "relative" },
  photoImg: { width: 84, height: 84, borderWidth: 1, borderColor: theme.border },
  playOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  photoRemove: { position: "absolute", top: 4, right: 4, backgroundColor: "rgba(0,0,0,0.7)", padding: 4 },
  photoArrow: {
    position: "absolute",
    top: "50%",
    width: 24,
    height: 24,
    marginTop: -12,
    backgroundColor: "rgba(0,0,0,0.7)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  photoArrowLeft: { left: 4 },
  photoArrowRight: { right: 4 },
  photoEmpty: { width: "100%", padding: spacing.md, borderWidth: 1, borderColor: theme.border, borderStyle: "dashed" },
  photoEmptyText: { color: theme.textMuted, fontSize: 12, textAlign: "center" },
  photoUploading: {
    width: 84,
    height: 84,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.primary,
    backgroundColor: "rgba(212, 175, 55, 0.08)",
    gap: 4,
  },
  photoUploadingText: {
    color: theme.primary,
    fontSize: 9,
    letterSpacing: 1,
    fontWeight: "600",
  },
  errorText: { color: theme.error, fontSize: 12, marginTop: spacing.md },
  primaryBtn: { backgroundColor: theme.primary, paddingVertical: 16, alignItems: "center", marginTop: spacing.xl },
  primaryBtnText: { color: "#0A0A0A", fontSize: 12, fontWeight: "700", letterSpacing: 3 },
  divider: { height: 1, backgroundColor: theme.border, marginVertical: spacing.lg },
  readonlyBlock: {
    color: theme.textPrimary,
    fontSize: 13,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
    lineHeight: 19,
  },
  originalBlock: { marginTop: spacing.sm, borderColor: theme.borderSubtle, opacity: 0.7 },
  viewOriginalBtn: {
    flexDirection: "row", alignItems: "center", gap: 6,
    paddingVertical: spacing.sm, alignSelf: "flex-start",
  },
  viewOriginalText: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  // ---- Pending-approval section (manufacturer/admin view of uploads
  // queued for atelier moderation) ----
  pendingBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: spacing.lg,
    marginBottom: 4,
  },
  pendingBadgeText: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 3,
    fontWeight: "700",
  },
  pendingBadgeHint: {
    color: theme.textMuted,
    fontSize: 11,
    fontStyle: "italic",
    marginBottom: spacing.sm,
    lineHeight: 15,
  },
  // ---- Manual on-demand translate (CTA shown when viewer language differs
  // from the step's auto-translated language)
  translateBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    marginTop: spacing.lg,
    borderWidth: 1,
    borderColor: theme.primary,
    alignSelf: "stretch",
    minHeight: 44,
  },
  translateBtnText: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
  },
  // ---- Amendment actions (manufacturer/admin on completed steps) ----
  mfgAmendRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  secondaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: theme.primary,
    minHeight: 44,
  },
  secondaryBtnText: {
    color: theme.primary,
    fontSize: 11,
    letterSpacing: 2,
  },
  dangerBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: theme.danger,
    minHeight: 44,
  },
  dangerBtnText: {
    color: theme.danger,
    fontSize: 11,
    letterSpacing: 2,
  },
});
