/**
 * Shared StyleSheet for the Home screen module.
 *
 * Originally lived as one ~300-line block at the bottom of
 * `app/(app)/index.tsx`. Lifted here so individual sub-components
 * (filter bar, filter panel, order card, etc.) can import the same
 * style keys without duplicating them.
 */
import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const homeStyles = StyleSheet.create({
  // ---- Shell ----------------------------------------------------------
  safe: { flex: 1, backgroundColor: theme.bg },
  centerFull: { flex: 1, justifyContent: "center", alignItems: "center" },
  // ---- Header ---------------------------------------------------------
  header: { marginBottom: spacing.lg },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  brandText: { flexShrink: 1 },
  brandMark: { color: theme.primary, fontSize: 10, letterSpacing: 3 },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  welcome: {
    color: theme.textPrimary,
    fontSize: 22,
    marginTop: 4,
    fontWeight: "400",
  },
  iconBtn: {
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: theme.border,
  },
  // ---- Stats row ------------------------------------------------------
  statsRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: spacing.lg,
  },
  stat: {
    flex: 1,
    padding: spacing.md,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: theme.border,
  },
  statValue: { color: theme.primary, fontSize: 28, fontWeight: "300" },
  statLabel: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2,
    marginTop: 4,
  },
  // ---- CTA + admin link list ----------------------------------------
  cta: {
    backgroundColor: theme.primary,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: spacing.lg,
  },
  ctaText: {
    color: "#0A0A0A",
    fontSize: 12,
    letterSpacing: 3,
    fontWeight: "700",
  },
  adminLinks: { marginBottom: spacing.lg, gap: 0 },
  linkBtn: {
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  linkBtnText: {
    color: theme.textPrimary,
    fontSize: 12,
    letterSpacing: 2,
    flex: 1,
  },
  toolsSub: {
    color: theme.textMuted,
    fontSize: 9,
    letterSpacing: 1,
    marginTop: 3,
    fontStyle: "italic",
  },
  approvalsBadge: {
    backgroundColor: theme.primary,
    borderRadius: 999,
    minWidth: 22,
    height: 18,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  approvalsBadgeText: {
    color: "#0A0A0A",
    fontSize: 10,
    fontWeight: "700",
  },
  // ---- Order card -----------------------------------------------------
  orderCard: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
  },
  orderCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  orderRef: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  orderName: {
    color: theme.textPrimary,
    fontSize: 17,
    marginTop: 4,
    lineHeight: 22,
  },
  orderSub: {
    color: theme.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  progressText: {
    color: theme.textSecondary,
    fontSize: 11,
    letterSpacing: 1,
  },
  currentStep: { color: theme.textSecondary, fontSize: 12 },
  // ---- Empty state ---------------------------------------------------
  empty: {
    padding: spacing.xl,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  emptyTitle: {
    color: theme.textPrimary,
    fontSize: 16,
    marginBottom: spacing.sm,
  },
  emptyText: {
    color: theme.textSecondary,
    fontSize: 13,
    textAlign: "center",
  },
  // ---- Bulk select ---------------------------------------------------
  selectModeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  selectModeHint: { color: theme.textMuted, fontSize: 11 },
  selectToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  selectToggleText: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 2,
  },
  orderCardSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.surfaceElevated,
  },
  cardCheckbox: { marginTop: 6, alignItems: "flex-end" },
  orderRightCol: { alignItems: "flex-end", gap: 6 },
  bulkBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  bulkCancel: {
    flex: 1,
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  bulkCancelText: {
    color: theme.textSecondary,
    fontSize: 11,
    letterSpacing: 2,
  },
  bulkDelete: {
    flex: 2,
    flexDirection: "row",
    gap: 6,
    paddingVertical: spacing.md,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  bulkDeleteText: {
    color: "#0A0A0A",
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
  },
  // ---- Commission filters --------------------------------------------
  filterBar: { paddingTop: 4, paddingBottom: spacing.sm },
  filterBarRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  activeChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.primary,
    backgroundColor: "rgba(218,165,32,0.10)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
    maxWidth: 220,
  },
  activeChipText: {
    color: theme.textPrimary,
    fontSize: 11,
    flexShrink: 1,
  },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
  },
  filterToggleText: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "600",
  },
  filterCount: {
    backgroundColor: theme.primary,
    paddingHorizontal: 6,
    minWidth: 18,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    marginLeft: 4,
  },
  filterCountText: {
    color: "#0A0A0A",
    fontSize: 10,
    fontWeight: "700",
  },
  filterClear: {
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  filterClearText: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2,
  },
  filterPanel: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "rgba(255,255,255,0.03)",
    gap: 4,
  },
  filterLabel: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 2,
    marginTop: spacing.sm,
    marginBottom: 6,
  },
  filterSubLabel: {
    color: theme.textMuted,
    fontSize: 9,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.textPrimary,
    fontSize: 13,
    minHeight: 40,
  },
  dateRow: { flexDirection: "row", justifyContent: "space-between" },
  pickerToggle: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 40,
  },
  pickerToggleText: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: 13,
  },
  pickerToggleEmpty: { color: theme.textMuted },
  pickerList: {
    borderWidth: 1,
    borderColor: theme.border,
    borderTopWidth: 0,
    maxHeight: 200,
  },
  pickerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  pickerRowSel: { backgroundColor: "rgba(218,165,32,0.08)" },
  pickerRowName: { color: theme.textPrimary, fontSize: 13 },
  pickerRowSub: {
    color: theme.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  goRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
    marginTop: spacing.lg,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  goCancelBtn: {
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  goCancelText: {
    color: theme.textMuted,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "600",
  },
  goBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.primary,
    paddingHorizontal: 22,
    paddingVertical: 10,
  },
  goBtnDim: { opacity: 0.55 },
  goBtnText: {
    color: "#0A0A0A",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 3,
  },
});
