import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg || theme.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerEyebrow: { color: theme.primary, fontSize: 10, letterSpacing: 3 },
  headerTitle: { color: theme.textPrimary, fontSize: 18, marginTop: 2 },
  formLabel: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 3,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  sectionMeta: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  uploadBtn: {
    backgroundColor: theme.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-end",
  },
  uploadBtnText: {
    color: "#0A0A0A",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  extBadge: {
    minWidth: 44,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.primary,
    alignItems: "center",
  },
  extText: {
    color: theme.primary,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  rowName: { color: theme.textPrimary, fontSize: 13, fontWeight: "600" },
  rowMeta: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  iconBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  emptyText: {
    color: theme.textMuted,
    fontSize: 11,
    paddingVertical: spacing.lg,
    fontStyle: "italic",
    lineHeight: 16,
  },
  input: {
    color: theme.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.md,
    textAlignVertical: "top",
  },
  error: { color: theme.error, fontSize: 12, marginTop: spacing.md },
  primaryBtn: {
    backgroundColor: theme.primary,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: spacing.xl,
  },
  primaryBtnText: {
    color: "#0A0A0A",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 3,
  },
  emailBtn: {
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: -spacing.sm,
    marginBottom: spacing.md,
  },
  emailBtnText: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 3,
  },
});
