/**
 * Shared StyleSheet for the Users directory screen.
 * Lifted as-is from the original 465-line monolithic file.
 */
import { StyleSheet } from "react-native";
import { theme, spacing } from "@/src/theme";

export const usersStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    gap: spacing.sm,
  },
  eyebrow: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  title: { color: theme.textPrimary, fontSize: 18, marginTop: 2 },
  addBtn: {
    backgroundColor: theme.primary,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  chipsWrap: {
    height: 56,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderSubtle,
  },
  chipsRow: {
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    gap: spacing.sm,
  },
  chip: {
    height: 36,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  chipSel: { borderColor: theme.primary },
  chipText: { color: theme.textSecondary, fontSize: 10, letterSpacing: 2 },
  chipTextSel: { color: theme.primary },
  empty: {
    padding: spacing.xl,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  emptyText: {
    color: theme.textSecondary,
    fontSize: 13,
    marginBottom: spacing.md,
  },
  addPill: {
    borderWidth: 1,
    borderColor: theme.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  addPillText: { color: theme.primary, fontSize: 10, letterSpacing: 2 },
  userRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: spacing.sm,
  },
  userName: { color: theme.textPrimary, fontSize: 14 },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  contactText: { color: theme.textSecondary, fontSize: 11, flexShrink: 1 },
  subFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
    flexWrap: "wrap",
  },
  missingChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
  },
  missingChipSel: { backgroundColor: theme.primary },
  missingChipText: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "600",
  },
  missingChipTextSel: { color: "#0A0A0A" },
  missingBadge: {
    backgroundColor: theme.primary,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
  },
  missingBadgeSel: { backgroundColor: "#0A0A0A" },
  missingBadgeText: { color: "#0A0A0A", fontSize: 10, fontWeight: "700" },
  missingBadgeTextSel: { color: theme.primary },
  subFilterHint: {
    color: theme.textMuted,
    fontSize: 10,
    letterSpacing: 1,
    fontStyle: "italic",
  },
  aliasRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  aliasLabel: { color: theme.textMuted, fontSize: 11, letterSpacing: 1 },
  aliasValue: {
    color: theme.primary,
    fontSize: 12,
    letterSpacing: 1,
    marginRight: 4,
  },
  aliasInput: {
    color: theme.primary,
    fontSize: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.primary,
    paddingVertical: 2,
    paddingHorizontal: 0,
  },
  userEmail: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  userMeta: {
    color: theme.primary,
    fontSize: 10,
    letterSpacing: 2,
    marginTop: 4,
  },
  autoFwdBox: { alignItems: "center", gap: 4, marginLeft: spacing.md },
  autoFwdLabel: { color: theme.primary, fontSize: 9, letterSpacing: 1 },
  actionsCol: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.sm,
    gap: 6,
  },
  actionBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
});
